DROP TABLE IF EXISTS `account_movements`;

CREATE TABLE `account_movements` (
  `account_movement_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `my_iban` varchar(34) NOT NULL,
  `my_bic` varchar(11) NOT NULL,
  `my_accountnumber` bigint(10) unsigned NOT NULL,
  `my_bankcode` int(8) unsigned NOT NULL,
  `booking_date` date NOT NULL,
  `value_date` date NOT NULL,
  `invoice_date` date DEFAULT NULL,
  `other_iban` varchar(34) DEFAULT NULL,
  `other_bic` varchar(11) DEFAULT NULL,
  `other_accountnumber` bigint(10) unsigned DEFAULT NULL,
  `other_bankcode` int(8) unsigned DEFAULT NULL,
  `other_name` varchar(54) DEFAULT NULL,
  `charge_value` decimal(15,2) DEFAULT NULL,
  `charge_currency` varchar(3) DEFAULT NULL,
  `original_value` decimal(15,2) DEFAULT NULL,
  `original_currency` varchar(3) DEFAULT NULL,
  `movement_value` decimal(15,2) NOT NULL,
  `movement_currency` varchar(3) NOT NULL,
  `movement_reason` text,
  `movement_type_code` int(3) NOT NULL,
  `movement_type_text` varchar(27) DEFAULT NULL,
  `customer_reference` varchar(16) NOT NULL,
  `bank_reference` varchar(16) DEFAULT NULL,
  `cancellation` int(1) unsigned NOT NULL,
  `additional_information` varchar(512) DEFAULT NULL,
  `additional_key` int(3) DEFAULT NULL,
  `prima_nota` varchar(10) DEFAULT NULL,
  `balance_date` date NOT NULL,
  `balance_value` decimal(15,2) NOT NULL,
  `balance_currency` varchar(3) NOT NULL,
  PRIMARY KEY (`account_movement_id`),
  UNIQUE KEY `hbci_i_03` (`my_iban`,`my_bic`,`my_accountnumber`,`my_bankcode`,`booking_date`,`value_date`,`movement_value`,`movement_currency`,`movement_type_code`,`customer_reference`,`cancellation`,`balance_date`,`balance_value`,`balance_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
