SET search_path TO moneyjinn;

ALTER TABLE `access_users` ALTER COLUMN `userid` RESTART WITH 9;
ALTER TABLE `access_groups` ALTER COLUMN `groupid` RESTART WITH 8;
ALTER TABLE `capitalsources` ALTER COLUMN `capitalsourceid` RESTART WITH 1;
ALTER TABLE `postingaccounts` ALTER COLUMN `postingaccountid` RESTART WITH 1;
ALTER TABLE `contractpartners` ALTER COLUMN `contractpartnerid` RESTART WITH 1;
ALTER TABLE `contractpartneraccounts` ALTER COLUMN `contractpartneraccountid` RESTART WITH 1;
ALTER TABLE `contractpartnermatchings` ALTER COLUMN `contractpartnermatchingid` RESTART WITH 1;
ALTER TABLE `etf` ALTER COLUMN `etfid` RESTART WITH 5;
ALTER TABLE `etfflows` ALTER COLUMN `etfflowid` RESTART WITH 12;
ALTER TABLE `etfpreliminarylumpsum` ALTER COLUMN `etfpreliminarylumpsumid` RESTART WITH 3;
ALTER TABLE `moneyflows` ALTER COLUMN `moneyflowid` RESTART WITH 20;
ALTER TABLE `moneyflowsplitentries` ALTER COLUMN `moneyflowsplitentryid` RESTART WITH 3;
ALTER TABLE `moneyflowreceipts` ALTER COLUMN `moneyflowreceiptid` RESTART WITH 3;
ALTER TABLE `monthlysettlements` ALTER COLUMN `monthlysettlementid` RESTART WITH 52;
ALTER TABLE `predefmoneyflows` ALTER COLUMN `predefmoneyflowid` RESTART WITH 1;
ALTER TABLE `impmoneyflowreceipts` ALTER COLUMN `impmoneyflowreceiptid` RESTART WITH 3;
ALTER TABLE `impmoneyflows` ALTER COLUMN `impmoneyflowid` RESTART WITH 1;
ALTER TABLE `impmonthlysettlements` ALTER COLUMN `impmonthlysettlementid` RESTART WITH 1;
ALTER TABLE `imp_data` ALTER COLUMN `dataid` RESTART WITH 1;
ALTER TABLE `cmp_data_formats` ALTER COLUMN `formatid` RESTART WITH 1;

DELETE FROM `cmp_data_formats`;
DELETE FROM `imp_mapping_partner`;
DELETE FROM `imp_mapping_source`;
DELETE FROM `imp_data`;
DELETE FROM `impmonthlysettlements`;
DELETE FROM `impmoneyflows`;
DELETE FROM `impmoneyflowreceipts`;
DELETE FROM `impbalance`;
DELETE FROM `predefmoneyflows`;
DELETE FROM `monthlysettlements`;
DELETE FROM `moneyflowreceipts`;
DELETE FROM `moneyflowsplitentries`;
DELETE FROM `moneyflows`;
DELETE FROM `etfpreliminarylumpsum`;
DELETE FROM `etfvalues`;
DELETE FROM `etfflows`;
DELETE FROM `etf`;
DELETE FROM `contractpartneraccounts`;
DELETE FROM `contractpartnermatchings`;
DELETE FROM `contractpartners`;
DELETE FROM `postingaccounts`;
DELETE FROM `capitalsources`;
DELETE FROM `settings`;
DELETE FROM `access_relation`;
DELETE FROM `access_groups`;
DELETE FROM `access_users`;